### ISSUE TITLE
git push origin challenge-02

### ISSUE THREAD

**Issue by marinhoOliv** [marinhoOliv/curso-javascript-ninja#1]
fala Fernando, blza man?
Estou com um erro ao executar o 'push':
ERROR: The key you are authenticating with has been marked as read only.
não consigo alterar o status da key. Poderia me ajudar nisso?
abs

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @marinhoOliv! Consegue abrir essa issue no repositório principal do curso? Você abriu no seu próprio repositório =)

Mas você vai precisar criar uma nova chave. Seguindo esse tutorial você consegue fazer da forma correta:
https://help.github.com/articles/connecting-to-github-with-ssh/

**Comment by marinhoOliv** [comment]
Valeu @fdaciuk eu não estava marcando o check box para permitir a escrita.

**Comment by fdaciuk** [comment]
Show! Qualquer coisa avisa ae :D
